### ISSUE TITLE
Caching results

### ISSUE THREAD

**Issue by jskopek** [sokanu/frame#3]

**Comment by jskopek** [comment]
Images are now cached after they have been generated. Here's the basic summary:

A request to an image will first hit the cache to see if the request has already been served in the past. If so, the cache will return the generated image path, and the server redirects the request nearly instantly. If the cache does not contain the image, the database is queried to determine if the image has been served in the past; if so, the cache is populated and the request is redirected. If the requested image is totally new, the original image is pulled down and modified, then saved and the path stored in cache.

This implementation makes for really fast overall performance, as the vast majority of requests are simple memcache get -> redirection responses

**Comment by sfard** [comment]
Nice JM

**Comment by jskopek** [comment]
Thanks!
